---
title: "Data Tidying"
author: "Jim Magdanz"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, let’s load dplyr and tidyr:

```{r libraries, warning=F, chunk=F}
library(dplyr)
library(tidyr)
```

Then let’s read in the data and take a look at it. Read catch data from [Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.] (https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1)

```{r load data, echo=FALSE}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```
'Select' the columns we need for analysis

```{r select data for catch clean}
catch_clean <- catch_df %>%
#  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode) %>%  # same as above, but subtracts rather than includes columns 
  gather(key="species", value = "catch", -Region, -Year) %>% # undo previous
  # spread(key="species", value = "catch") %>%
  rename(catch_thousands = catch) # rename a column to indicate units
  
  
head(catch_clean)

```

Move from wide to long form, using gather function. The "key" is what you are associating columns, here, "species"

```{r Gather}


```
